# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.0-rc3"
manifest_format = "2.0"
project_hash = "7e232863c31929190d5fd288f2e6f2ef660269fd"

[[deps.AlgebraFrames]]
path = "../AlgebraFrames.jl"
uuid = "91245b94-7320-4a9d-ac3a-8d3b3e6674af"
version = "0.1.0"
